# Generated by Django 4.0.1 on 2022-01-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_alter_drive_file_alter_drive_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
