# Generated by Django 4.0.1 on 2022-01-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_remove_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='file',
            field=models.FileField(max_length=255, upload_to='uploads/'),
        ),
    ]
